#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 14 22:40:20 2020

@author: devyanshitiwari
find the occurence of a substring in a given string
"""

def count_substring(string, sub_string):
    x = string.count(sub_string)
    return x

if __name__ == '__main__':
    string = raw_input().strip()
    sub_string = raw_input().strip()
    
    count = count_substring(string, sub_string)
    print count